### ISSUE TITLE
Hex values should not be preceded by #

### ISSUE THREAD

**Issue by fmunch** [Thomashighbaugh/base16-vice-scheme#7]
Commit d918812 added # to hex values, which breaks theme builds (see for example https://github.com/fmunch/base16-mate-terminal/actions/runs/4190147952/jobs/7263251387).

The [documentation](https://github.com/chriskempson/base16/blob/main/file.md) recommends against using # :
> Hexadecimal color values should not be preceded by a "#".

**Comment by Thomashighbaugh** [comment]
Thanks for this fixing it now

**Comment by Thomashighbaugh** [comment]
Done problem should be solved
